Physics documentation
PTS3-S34A/Physics pull request #10
Opened 2017-01-10 09:32 UTC by marcgroos

2017-01-10 13:45 UTC, Laugslander requested changes
Aantal parameters en returntypen nog documenteren.

2017-01-10 13:45 UTC, Laugslander commented on Soccar [Physics]/src/nl/soccar/physics/GameEngine.java
> +     * @param player
Parameters documenteren.

2017-01-10 13:45 UTC, Laugslander commented on Soccar [Physics]/src/nl/soccar/physics/GameEngine.java
> +     * @param player
Parameter documenteren.

2017-01-10 13:45 UTC, Laugslander commented on Soccar [Physics]/src/nl/soccar/physics/GameEngine.java
> +     * @param object
Parameter documenteren.

2017-01-10 13:45 UTC, Laugslander commented on Soccar [Physics]/src/nl/soccar/physics/GameEngine.java
> +     * @param object
Parameter documenteren.

2017-01-10 13:45 UTC, Laugslander commented on Soccar [Physics]/src/nl/soccar/physics/models/BallPhysics.java
> +
Enter verwijderen.

2017-01-10 13:45 UTC, Laugslander commented on Soccar [Physics]/src/nl/soccar/physics/models/WheelPhysics.java
> +     * @return boolean
Parameter documenteren.

2017-01-10 13:45 UTC, Laugslander commented on Soccar [Physics]/src/nl/soccar/physics/models/WheelPhysics.java
> +     * @return boolean
Parameter documenteren.

2017-01-10 13:45 UTC, Laugslander commented on Soccar [Physics]/src/nl/soccar/physics/models/ObstaclePhysics.java
> +     * @return The obstacle object.
Enter toevoegen tussen beschrijving methode en parameters.

2017-01-10 13:45 UTC, Laugslander commented on Soccar [Physics]/src/nl/soccar/physics/models/CarPhysics.java
> +     * @return boolean
Returntype documenteren.

2017-01-11 08:59 UTC, TehMessiah commented
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [GameEngine.java#L24](https://github.com/PTS3-S34A/Physics/blob/30457c47c54e1bc379b1197253d0b45899367c74/Soccar [Physics]/src/nl/soccar/physics/GameEngine.java#L24): Remove this unused "room" private field. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AS1068)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [GameEngine.java#L130](https://github.com/PTS3-S34A/Physics/blob/30457c47c54e1bc379b1197253d0b45899367c74/Soccar [Physics]/src/nl/soccar/physics/GameEngine.java#L130): Replace this "switch" statement by "if" statements to increase readability. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AS1301)

2017-01-18 10:40 UTC, Laugslander requested changes

2017-01-18 10:40 UTC, Laugslander commented on Soccar [Physics]/src/nl/soccar/physics/models/CarPhysics.java
> +     *1
Random 1 verwijderen.

2017-01-18 10:40 UTC, Laugslander commented on Soccar [Physics]/src/nl/soccar/physics/models/BallPhysics.java
> +     *1
Random 1 verwijderen.

2017-01-18 10:42 UTC, Laugslander approved these changes

2017-01-18 10:59 UTC, merged

2017-01-18 11:00 UTC, BeeHiveJava commented
retest this please